// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BenchmarkRegistries() {
  return window['go']['main']['App']['BenchmarkRegistries']();
}

export function CancelTask() {
  return window['go']['main']['App']['CancelTask']();
}

export function Deploy() {
  return window['go']['main']['App']['Deploy']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenInstallDirectory() {
  return window['go']['main']['App']['OpenInstallDirectory']();
}

export function OpenService() {
  return window['go']['main']['App']['OpenService']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function TestCurrentRegistry() {
  return window['go']['main']['App']['TestCurrentRegistry']();
}
