// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BenchmarkRegistries():Promise<Array<main.RegistryResult>>;

export function CancelTask():Promise<void>;

export function Deploy():Promise<void>;

export function GetStatus():Promise<main.Status>;

export function OpenInstallDirectory():Promise<void>;

export function OpenService():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<main.Config>;

export function StartService(arg1:boolean):Promise<void>;

export function StopService():Promise<void>;

export function TestCurrentRegistry():Promise<main.RegistryResult>;
